

import math

# HAT / I2C
I2C_BUS = 8
MOTOR_SHUTDOWN_TIMEOUT_S = 0.5

# Encoder / gearbox
ENCODER_TICKS_PER_MOTOR_REV = 14.0
GEAR_RATIO = 50.0
TICKS_PER_SPROCKET_REV = ENCODER_TICKS_PER_MOTOR_REV * GEAR_RATIO  

# Provis drive diameter
EFFECTIVE_SPROCKET_DIAMETER_MM = 35.0
TICKS_PER_MM = TICKS_PER_SPROCKET_REV / (
    math.pi * EFFECTIVE_SPROCKET_DIAMETER_MM
)

# Robot geometry
TRACK_OUTSIDE_WIDTH_MM = 123.0
TRACK_INNER_GAP_MM = 92.5
TRACK_WIDTH_MM = (TRACK_OUTSIDE_WIDTH_MM - TRACK_INNER_GAP_MM) / 2.0  # 15.25
TRACK_CENTRE_SPACING_MM = TRACK_INNER_GAP_MM + TRACK_WIDTH_MM          # 107.75

# Skid-steer correction.
TURN_CALIBRATION = 1.0

# Direction correction.

LEFT_MOTOR_SIGN = 1
RIGHT_MOTOR_SIGN = 1

# Motion defaults.
DEFAULT_DRIVE_SPEED = 5
DEFAULT_TURN_SPEED = 4
MIN_CONTROLLED_SPEED = 2
MAX_TEST_SPEED = 15

CONTROL_PERIOD_S = 0.02      # 50 Hz command refresh
POSITION_TOLERANCE_TICKS = 8
SLOWDOWN_DISTANCE_MM = 40.0
STOP_SETTLE_TIME_S = 0.08
